name-template: v$RESOLVED_VERSION
tag-template: v$RESOLVED_VERSION
categories:
  - title: ✨ Features
    label: enhancement
  - title: 🐛 Bug Fixes
    label: bug
  - title: 🔧 Maintenance
    label: chore
  - title: 📦 Dependencies
    label: dependencies
  - title: 📝 Documentation
    label: documentation
version-resolver:
  major:
    labels:
      - major
  minor:
    labels:
      - minor
      - enhancement
  patch:
    labels:
      - patch
      - bug
  default: patch
template: |
  ## Changes

  $CHANGES

  ## Contributors

  $CONTRIBUTORS
